# This is a basic workflow to help you get started with Actions

name: caller-workflow

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  terraform_plan:
    name: terraform 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform hashicorp
        uses: hashicorp/setup-terraform@v2 
        with:
          terraform_version: 1.1.7
      
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::528519205020:role/pinkesh-TU
          aws-region: us-east-1
      
      - name: terraform init  
        run: 
          terraform init -reconfigure 
      
      - name: terraform apply
        run:
          terraform apply -auto-approve

      # - name: echo
      #   run:
      #     echo "$aws-access-key-id"
